// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ijlynivfhp.WEBService.OrderServices.Context;

namespace ijlynivfhp.WEBService.OrderServices.Migrations
{
    [DbContext(typeof(OrderContext))]
    partial class OrderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ijlynivfhp.WEBService.OrderServices.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Createtime")
                        .HasColumnType("datetime");

                    b.Property<string>("OrderAddress")
                        .HasColumnType("text");

                    b.Property<string>("OrderFlag")
                        .HasColumnType("text");

                    b.Property<string>("OrderName")
                        .HasColumnType("text");

                    b.Property<string>("OrderRemark")
                        .HasColumnType("text");

                    b.Property<string>("OrderSn")
                        .HasColumnType("text");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("OrderTel")
                        .HasColumnType("text");

                    b.Property<string>("OrderTotalPrice")
                        .HasColumnType("text");

                    b.Property<string>("OrderType")
                        .HasColumnType("text");

                    b.Property<DateTime>("Paytime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Sendtime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Successtime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Updatetime")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ijlynivfhp.WEBService.OrderServices.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ItemTotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("OrderSn")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
